# Visit 2.13.3 log file
ScriptVersion = "2.13.3"
if ScriptVersion != Version():
    print "This script is for VisIt %s. It may not work with version %s" % (ScriptVersion, Version())
ShowAllWindows()
SetActivePlots()
DeleteActivePlots()
OpenDatabase("/home/wvn/dirs/sandbox/cfd-data/NASA-comparison/data-raws/data-137x97-2ndorder/mu_t_0050000.hdf5", 0)
# The UpdateDBPluginInfo RPC is not supported in the VisIt module so it will not be logged.
metadata = GetMetaData("/home/wvn/dirs/sandbox/cfd-data/NASA-comparison/data-raws/data-137x97-2ndorder/mu_t_0050000.hdf5", -1)
DefineVectorExpression("xyz", "{<x                   >,<y                   >,<z                   >}")
DefineScalarExpression("operators/ConnectedComponents/Mesh", "cell_constant(<Mesh>, 0.)")
DefineCurveExpression("operators/DataBinning/1D/Mesh", "cell_constant(<Mesh>, 0)")
DefineScalarExpression("operators/DataBinning/2D/Mesh", "cell_constant(<Mesh>, 0)")
DefineScalarExpression("operators/DataBinning/3D/Mesh", "cell_constant(<Mesh>, 0)")
DefineScalarExpression("operators/Flux/Mesh", "cell_constant(<Mesh>, 0.)")
DefineScalarExpression("operators/IntegralCurve/xyz", "cell_constant(<xyz>, 0.)")
DefineScalarExpression("operators/IntegralCurve/", "cell_constant(<>, 0.)")
DefineScalarExpression("operators/IntegralCurve/Vel                ", "cell_constant(<Vel                >, 0.)")
DefineScalarExpression("operators/LCS/xyz", "cell_constant(<xyz>, 0.)")
DefineVectorExpression("operators/LCS/xyz", "cell_constant(<xyz>, 0.)")
DefineScalarExpression("operators/LCS/", "cell_constant(<>, 0.)")
DefineVectorExpression("operators/LCS/", "cell_constant(<>, 0.)")
DefineScalarExpression("operators/LCS/Vel                ", "cell_constant(<Vel                >, 0.)")
DefineVectorExpression("operators/LCS/Vel                ", "cell_constant(<Vel                >, 0.)")
DefineCurveExpression("operators/Lagrangian/xyz", "cell_constant(<xyz>, 0.)")
DefineCurveExpression("operators/Lagrangian/", "cell_constant(<>, 0.)")
DefineCurveExpression("operators/Lagrangian/Vel                ", "cell_constant(<Vel                >, 0.)")
DefineScalarExpression("operators/LimitCycle/xyz", "cell_constant(<xyz>, 0.)")
DefineCurveExpression("operators/LimitCycle/xyz", "cell_constant(<xyz>, 0.)")
DefineScalarExpression("operators/LimitCycle/", "cell_constant(<>, 0.)")
DefineCurveExpression("operators/LimitCycle/", "cell_constant(<>, 0.)")
DefineScalarExpression("operators/LimitCycle/Vel                ", "cell_constant(<Vel                >, 0.)")
DefineCurveExpression("operators/LimitCycle/Vel                ", "cell_constant(<Vel                >, 0.)")
DefineCurveExpression("operators/Lineout/x                   ", "cell_constant(<x                   >, 0.)")
DefineCurveExpression("operators/Lineout/y                   ", "cell_constant(<y                   >, 0.)")
DefineCurveExpression("operators/Lineout/z                   ", "cell_constant(<z                   >, 0.)")
DefineCurveExpression("operators/Lineout/mu_t                ", "cell_constant(<mu_t                >, 0.)")
DefineCurveExpression("operators/Lineout/UVel                ", "cell_constant(<UVel                >, 0.)")
DefineCurveExpression("operators/Lineout/VVel                ", "cell_constant(<VVel                >, 0.)")
DefineCurveExpression("operators/Lineout/Temperature         ", "cell_constant(<Temperature         >, 0.)")
DefineCurveExpression("operators/Lineout/nu                  ", "cell_constant(<nu                  >, 0.)")
DefineScalarExpression("operators/ModelFit/model", "point_constant(<Mesh>, 0)")
DefineScalarExpression("operators/ModelFit/distance", "point_constant(<Mesh>, 0)")
DefineScalarExpression("operators/Poincare/xyz", "cell_constant(<xyz>, 0.)")
DefineScalarExpression("operators/Poincare/", "cell_constant(<>, 0.)")
DefineScalarExpression("operators/Poincare/Vel                ", "cell_constant(<Vel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Sum/x                   ", "cell_constant(<x                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Sum/y                   ", "cell_constant(<y                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Sum/z                   ", "cell_constant(<z                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Sum/mu_t                ", "cell_constant(<mu_t                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Sum/UVel                ", "cell_constant(<UVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Sum/VVel                ", "cell_constant(<VVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Sum/Temperature         ", "cell_constant(<Temperature         >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Sum/nu                  ", "cell_constant(<nu                  >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Mean/x                   ", "cell_constant(<x                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Mean/y                   ", "cell_constant(<y                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Mean/z                   ", "cell_constant(<z                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Mean/mu_t                ", "cell_constant(<mu_t                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Mean/UVel                ", "cell_constant(<UVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Mean/VVel                ", "cell_constant(<VVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Mean/Temperature         ", "cell_constant(<Temperature         >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Mean/nu                  ", "cell_constant(<nu                  >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Variance/x                   ", "cell_constant(<x                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Variance/y                   ", "cell_constant(<y                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Variance/z                   ", "cell_constant(<z                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Variance/mu_t                ", "cell_constant(<mu_t                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Variance/UVel                ", "cell_constant(<UVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Variance/VVel                ", "cell_constant(<VVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Variance/Temperature         ", "cell_constant(<Temperature         >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Variance/nu                  ", "cell_constant(<nu                  >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Std. Dev./x                   ", "cell_constant(<x                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Std. Dev./y                   ", "cell_constant(<y                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Std. Dev./z                   ", "cell_constant(<z                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Std. Dev./mu_t                ", "cell_constant(<mu_t                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Std. Dev./UVel                ", "cell_constant(<UVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Std. Dev./VVel                ", "cell_constant(<VVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Std. Dev./Temperature         ", "cell_constant(<Temperature         >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Std. Dev./nu                  ", "cell_constant(<nu                  >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Slope/x                   ", "cell_constant(<x                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Slope/y                   ", "cell_constant(<y                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Slope/z                   ", "cell_constant(<z                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Slope/mu_t                ", "cell_constant(<mu_t                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Slope/UVel                ", "cell_constant(<UVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Slope/VVel                ", "cell_constant(<VVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Slope/Temperature         ", "cell_constant(<Temperature         >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Slope/nu                  ", "cell_constant(<nu                  >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Residuals/x                   ", "cell_constant(<x                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Residuals/y                   ", "cell_constant(<y                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Residuals/z                   ", "cell_constant(<z                   >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Residuals/mu_t                ", "cell_constant(<mu_t                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Residuals/UVel                ", "cell_constant(<UVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Residuals/VVel                ", "cell_constant(<VVel                >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Residuals/Temperature         ", "cell_constant(<Temperature         >, 0.)")
DefineScalarExpression("operators/StatisticalTrends/Residuals/nu                  ", "cell_constant(<nu                  >, 0.)")
DefineVectorExpression("operators/SurfaceNormal/Mesh", "cell_constant(<Mesh>, 0.)")
DefineVectorExpression("phys_transform", "{<x                   >,<y                   >,<z                   >}")
AddPlot("Pseudocolor", "mu_t                ", 1, 1)
AddOperator("Displace", 1)
DisplaceAtts = DisplaceAttributes()
DisplaceAtts.factor = 1
DisplaceAtts.variable = "phys_transform"
SetOperatorOptions(DisplaceAtts, 1)
DrawPlots()
Query("Lineout", end_point=(0.97, 0.025, 0), start_point=(0.97, 0, 0), vars=("mu_t                "))
SetActiveWindow(2)
ExportDBAtts = ExportDBAttributes()
ExportDBAtts.allTimes = 0
ExportDBAtts.dirname = "."
ExportDBAtts.filename = "./output_mu_t_nasa"
ExportDBAtts.timeStateFormat = "_%04d"
ExportDBAtts.db_type = "Curve2D"
ExportDBAtts.db_type_fullname = "Curve2D_1.0"
ExportDBAtts.variables = ("mu_t                ")
ExportDBAtts.writeUsingGroups = 0
ExportDBAtts.groupSize = 48
ExportDBAtts.opts.types = ()
ExportDBAtts.opts.help = ""
ExportDatabase(ExportDBAtts)
